### ISSUE TITLE
How do I adjust my 401k contribution?

### ISSUE THREAD

**Issue by mguterl** [gaslight/handbook#24]
/cc @xero6 @merrilee

**Comment by merrilee** [comment]
Employees can change their contribution amounts on the first day of any
month.  They can stop their contributions at any time.

**Comment by mguterl** [comment]
Thanks @merrilee, but how do I make the change?

**Comment by merrilee** [comment]
What kind of changes are you talking about?  If it's the amount of money
then you do it through me.  If you want to make changes to how it's
invested I will have to inquire about that.

**Comment by mguterl** [comment]
@merrilee - just the percentage. The investments have to be changed through Nationwide. I'm going to open a pull request to document that percentage changes will go through you. Thanks! :+1:

**Comment by mguterl** [comment]
@merrilee - please don't make any changes to my contribution. I just wanted to know how.

**Comment by merrilee** [comment]
Oh, ok.
